from gym.envs.registration import register

register(
    id="battlesnake-9x9-easy-v0",
    entry_point="gym_battlesnake.envs:BattlesnakeEnv9x9Easy",
)
register(
    id="battlesnake-9x9-medium-v0",
    entry_point="gym_battlesnake.envs:BattlesnakeEnv9x9Medium",
)
register(
    id="battlesnake-9x9-hard-v0",
    entry_point="gym_battlesnake.envs:BattlesnakeEnv9x9Hard",
)
register(
    id="battlesnake-9x9-easy-sparse-v0",
    entry_point="gym_battlesnake.envs:BattlesnakeEnv9x9EasySparse",
)
register(
    id="battlesnake-9x9-medium-sparse-v0",
    entry_point="gym_battlesnake.envs:BattlesnakeEnv9x9MediumSparse",
)
register(
    id="battlesnake-9x9-hard-sparse-v0",
    entry_point="gym_battlesnake.envs:BattlesnakeEnv9x9HardSparse",
)

register(
    id="battlesnake-12x12-easy-v0",
    entry_point="gym_battlesnake.envs:BattlesnakeEnv12x12Easy",
)
register(
    id="battlesnake-12x12-medium-v0",
    entry_point="gym_battlesnake.envs:BattlesnakeEnv12x12Medium",
)
register(
    id="battlesnake-12x12-hard-v0",
    entry_point="gym_battlesnake.envs:BattlesnakeEnv12x12Hard",
)
register(
    id="battlesnake-12x12-easy-sparse-v0",
    entry_point="gym_battlesnake.envs:BattlesnakeEnv12x12EasySparse",
)
register(
    id="battlesnake-12x12-medium-sparse-v0",
    entry_point="gym_battlesnake.envs:BattlesnakeEnv12x12MediumSparse",
)
register(
    id="battlesnake-12x12-hard-sparse-v0",
    entry_point="gym_battlesnake.envs:BattlesnakeEnv12x12HardSparse",
)

register(
    id="battlesnake-15x15-easy-v0",
    entry_point="gym_battlesnake.envs:BattlesnakeEnv15x15Easy",
)
register(
    id="battlesnake-15x15-medium-v0",
    entry_point="gym_battlesnake.envs:BattlesnakeEnv15x15Medium",
)
register(
    id="battlesnake-15x15-hard-v0",
    entry_point="gym_battlesnake.envs:BattlesnakeEnv15x15Hard",
)
register(
    id="battlesnake-15x15-easy-sparse-v0",
    entry_point="gym_battlesnake.envs:BattlesnakeEnv15x15EasySparse",
)
register(
    id="battlesnake-15x15-medium-sparse-v0",
    entry_point="gym_battlesnake.envs:BattlesnakeEnv15x15MediumSparse",
)
register(
    id="battlesnake-15x15-hard-sparse-v0",
    entry_point="gym_battlesnake.envs:BattlesnakeEnv15x15HardSparse",
)

register(
    id="battlesnake-18x18-easy-v0",
    entry_point="gym_battlesnake.envs:BattlesnakeEnv18x18Easy",
)
register(
    id="battlesnake-18x18-medium-v0",
    entry_point="gym_battlesnake.envs:BattlesnakeEnv18x18Medium",
)
register(
    id="battlesnake-18x18-hard-v0",
    entry_point="gym_battlesnake.envs:BattlesnakeEnv18x18Hard",
)
register(
    id="battlesnake-18x18-easy-sparse-v0",
    entry_point="gym_battlesnake.envs:BattlesnakeEnv18x18EasySparse",
)
register(
    id="battlesnake-18x18-medium-sparse-v0",
    entry_point="gym_battlesnake.envs:BattlesnakeEnv18x18MediumSparse",
)
register(
    id="battlesnake-18x18-hard-sparse-v0",
    entry_point="gym_battlesnake.envs:BattlesnakeEnv18x18HardSparse",
)
